# MIoT spec: https://home.miot-spec.com/spec/zhimi.humidifier.ca4
# Instance (v2): https://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:humidifier:0000A00E:zhimi-ca4:2

external_components:
  source: github://dhewg/esphome-miot@main

esphome:
  name: humidifier
  friendly_name: Air Humidifier
  comment: Smartmi Evaporative Humidifier 2 (zhimi.humidifier.ca4)
  project:
    name: "dhewg.esphome-miot"
    version: "zhimi.humidifier.ca4"

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: y
    advanced:
      # Required on some devices due to EFUSE layout differences
      ignore_efuse_custom_mac: true
      ignore_efuse_mac_crc: true

logger:
  level: INFO

api:
  encryption:
    key: !secret api_encryption_key
  reboot_timeout: 0s
  services:
    - service: mcu_command
      variables:
        command: string
      then:
        - lambda: "id(miot_main).queue_command(command);"

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    password: !secret wifi_ap_password

captive_portal:

uart:
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 115200

time:
  - platform: homeassistant
    id: ha_time
    timezone: Europe/Amsterdam

miot:
  id: miot_main

# Controls (writable MIoT properties)

fan:
  - platform: "miot"
    name: "Fan"
    state:
      miot_siid: 2
      miot_piid: 1
    speed:
      miot_siid: 2
      miot_piid: 5
      min_value: 0
      max_value: 3

switch:
  - platform: "miot"
    miot_siid: 2
    miot_piid: 8
    name: "Dry"
    icon: mdi:water-minus

  # "Alarm" is the device buzzer / notification sounds in the official MIoT spec.
  - platform: "miot"
    miot_siid: 4
    miot_piid: 1
    name: "Notification Sounds"
    icon: mdi:volume-high
    entity_category: config

  - platform: "miot"
    miot_siid: 6
    miot_piid: 1
    name: "Child Lock"
    icon: mdi:lock
    entity_category: config

  - platform: "miot"
    miot_siid: 7
    miot_piid: 5
    name: "Clean Mode"
    icon: mdi:water-minus
    entity_category: config

select:
  - platform: "miot"
    miot_siid: 5
    miot_piid: 2
    name: "Display Brightness"
    icon: mdi:brightness-6
    entity_category: config
    options:
      0: "Dark"
      1: "Glimmer"
      2: "Brightest"

  # Region setting used by the MCU (writable).
  - platform: "miot"
    miot_siid: 7
    miot_piid: 4
    name: "Country Code"
    icon: mdi:earth
    entity_category: config
    options:
      0: "Unknown"
      1: "US"
      7: "RU"
      33: "FR"
      44: "EU (Europe)"
      81: "JP"
      82: "KR"
      86: "CN"

number:
  - platform: "miot"
    miot_siid: 2
    miot_piid: 6
    name: "Target Humidity"
    icon: mdi:water-percent
    unit_of_measurement: "%"
    min_value: 30
    max_value: 80
    step: 1

# Sensors (read-only MIoT properties)

sensor:
  - platform: "miot"
    miot_siid: 2
    miot_piid: 2
    name: "Device Fault Code"
    icon: mdi:alert-circle-outline
    entity_category: diagnostic

  - platform: "miot"
    miot_siid: 3
    miot_piid: 7
    name: "Temperature"
    unit_of_measurement: "°C"
    device_class: temperature
    state_class: measurement
    icon: mdi:thermometer

  - platform: "miot"
    miot_siid: 3
    miot_piid: 9
    name: "Relative Humidity"
    unit_of_measurement: "%"
    device_class: humidity
    state_class: measurement
    icon: mdi:water-percent

  - platform: "miot"
    miot_siid: 2
    miot_piid: 7
    name: "Water Level"
    unit_of_measurement: "%"
    state_class: measurement
    icon: mdi:cup-water
    filters:
      - clamp:
          min_value: 0
          max_value: 100
          ignore_out_of_range: true

  # "Speed Level" is a writable setpoint (200..2000, step 10) in the MIoT spec.
  - platform: "miot"
    miot_siid: 2
    miot_piid: 11
    name: "Motor Speed Setpoint"
    unit_of_measurement: "rpm"
    icon: mdi:fan
    entity_category: diagnostic

  - platform: "miot"
    miot_siid: 7
    miot_piid: 1
    name: "Actual Speed"
    unit_of_measurement: "rpm"
    icon: mdi:fan

  - platform: "miot"
    miot_siid: 2
    miot_piid: 9
    name: "Total Use Time"
    unit_of_measurement: "h"
    icon: mdi:timer-outline
    entity_category: diagnostic
    state_class: total_increasing
    filters:
      - multiply: 0.0002777778

  - platform: "miot"
    miot_siid: 7
    miot_piid: 3
    name: "Power Time"
    unit_of_measurement: "h"
    icon: mdi:timer
    entity_category: diagnostic
    state_class: measurement
    filters:
      - multiply: 0.0002777778

  - platform: "miot"
    miot_siid: 2
    miot_piid: 10
    name: "Last Button Pressed"
    icon: mdi:gesture-tap-button
    entity_category: diagnostic

  - platform: internal_temperature
    name: "MCU Temperature"
    unit_of_measurement: "°C"
    device_class: temperature
    state_class: measurement

  - platform: "miot"
    miot_siid: 3
    miot_piid: 8
    name: "Temperature (F)"
    unit_of_measurement: "°F"
    device_class: temperature
    state_class: measurement
    entity_category: diagnostic
